version: "3"
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

  backend:
    build:
      context: ./RGBMovie
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#     depends_on:
#       - db
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/rgb
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=12345

#   db:
#     image: mysql:8.1
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: rgb
#       MYSQL_PASSWORD: 12345
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
